#!/bin/sh

"$HOME/.profile"

WALLPAPERS=~/Pictures/wallpaper

# Make sure we are up-to-date
xrdb -load  "$HOME/.config/xresources/config"
xrdb -merge "$HOME/.config/xresources/colors/$(cat "$HOME/.theme")"

INFILES=$(tr '\n' ' ' <<-ENDINFILES
  $HOME/.config/herbstluftwm/config
  $HOME/.config/polybar/config
  $HOME/.config/dunst/dunstrc
  $HOME/.config/rofi/xresources
  $HOME/.config/sddm/Main.qml
ENDINFILES
)
for file in $INFILES; do
  preprocess "$file" &
done && wait

killall polybar
killall herbstclient
killall picom
killall dunst
killall notify_battery
killall flashfocus

"$HOME/.config/herbstluftwm/config"
xrdb -merge "$HOME/.config/rofi/xresources"
xrdb -merge "$HOME/.urxvt/config"

# user processes
dunst &
picom -b &
polybar bottom &
"$HOME/.config/herbstluftwm/notify_battery" &

# session configuration
theme_wallpaper=$(xrdb -query | awk '/*wallpaper:/{print $2}')
if [ -f "$WALLPAPERS/$theme_wallpaper" ]; then
  feh --no-fehbg --bg-fill "$WALLPAPERS/$theme_wallpaper" &
else
  # default wallpaper
  feh --no-fehbg --bg-fill $WALLPAPERS/yosemite.jpg &
fi
xsetroot -cursor_name left_ptr &

notify-send "Theme:" "$(sed 's/[-_]/ /g; s/\b\(.\)/\u\1/g' < "$HOME/.theme")"
