#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

killall polybar
killall herbstclient
killall compton

# set the background
#feh --bg-fill /boot/EFI/refind/theme/banner.png &
#xsetroot -cursor_name left_ptr -solid "${PALETTE[7]}"
wal -R

# remove all existing input binds
hc keyunbind --all
hc mouseunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# media keys
hc keybind XF86MonBrightnessDown    spawn light -U 5
hc keybind XF86MonBrightnessUp      spawn light -A 5
hc keybind XF86AudioMute            spawn pulsemixer --toggle-mute
hc keybind XF86AudioLowerVolume     spawn pulsemixer --change-volume -2
hc keybind XF86AudioRaiseVolume     spawn pulsemixer --change-volume +2
# session
hc keybind $Mod-Shift-q      quit
hc keybind $Mod-Shift-r      reload
hc keybind $Mod-z            spawn $HOME/.config/rofi/session.sh
hc keybind $Mod-x            spawn betterlockscreen -l
hc keybind $Mod-q            close
hc keybind $Mod-Return       spawn $HOME/.config/rofi/prompt.sh
hc keybind $Mod-Shift-Return spawn alacritty

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Shift-u split   top     0.5
hc keybind $Mod-Shift-o split   left    0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.01
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..4} )
tag_keys=( {1..4} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layout control
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 max vertical horizontal grid             \
               , cycle_layout +1

hc keybind $Mod-Shift-space                                                     \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout -1 max vertical horizontal grid             \
               , cycle_layout -1
# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace           cycle_monitor +1
hc keybind $Mod-Shift-BackSpace     cycle_monitor -1
hc keybind $Mod-Tab                 cycle +1
hc keybind $Mod-Shift-Tab           cycle -1
hc keybind $Mod-Control-Tab         cycle_frame +1
hc keybind $Mod-Shift-Control-Tab   cycle_frame -1
hc keybind $Mod-i                   jumpto urgent

# theme
hc attr theme.reset 1
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

#hc attr theme.active.color white
#hc attr theme.urgent.color white
hc attr theme.inner_width 0
hc attr theme.border_width 5
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 0

hc set window_gap 10
hc set frame_padding
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

hc detect_monitors
hc set_layout max

# colorscheme
unset palette
declare -A palette
while IFS=':' read -r key val; do
    palette+=(["$key"]="$val")
done < <(xrdb -query | grep "^*[^\.]" | xargs -n 2 | sed -e "s/\*//" -e "s/\s//")

hc attr theme.normal.color "${palette[color2]}"
hc attr theme.active.color "${palette[foreground]}"
hc attr theme.urgent.color "${palette[color3]}"

hc pad 0 52

# enable the compositor
compton -b &

# swap caps with escape
setxkbmap -option caps:swapescape &
xset r rate 500 50

# fix dpi cause it ain't working for some reason
xrandr --dpi 120/eDP-1

# panel
polybar top &
