#!/bin/sh

if ! [ -r /tmp/layout ]; then
  echo '/tmp/layout does not exist.'
  exit 0
fi

while read -r line; do
  tag="$(echo "$line" | grep -o "^[[:digit:]]\+:")"
  layout="$(echo "$line" | cut -c $((${#tag}+2))-)"
  echo "herbstclient load $(echo "$tag" | cut -c 1,$((${#tag}-1))) "$layout""
  herbstclient load $(echo "$tag" | cut -c 1,$((${#tag}-1))) "$layout"
done < /tmp/layout
